# Generated by Django 3.1.1 on 2020-09-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('name', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
